from project_g.domain.news import (
    NewsSource,
    SourceStatus,
    SourceType,
)

INITIAL_NEWS_SOURCES: tuple[NewsSource, ...] = (
    NewsSource(
        source_id="giants_official_news",
        name="Giants Official News",
        source_type=SourceType.WEBSITE,
        base_url="https://www.giants.jp/news/",
        is_official=True,
        status=SourceStatus.PAUSED,
        priority=100,
    ),
    NewsSource(
        source_id="giants_official_schedule",
        name="Giants Official Schedule",
        source_type=SourceType.WEBSITE,
        base_url="https://www.giants.jp/schedule/first-team/",
        is_official=True,
        status=SourceStatus.ENABLED,
        priority=98,
    ),
    NewsSource(
        source_id="npb_official_schedule",
        name="NPB Official Schedule",
        source_type=SourceType.WEBSITE,
        base_url="https://npb.jp/bis/2026/games/",
        is_official=True,
        status=SourceStatus.ENABLED,
        priority=96,
    ),
    NewsSource(
        source_id="npb_official_stats",
        name="NPB Official Stats",
        source_type=SourceType.WEBSITE,
        base_url="https://npb.jp/bis/2026/stats/",
        is_official=True,
        status=SourceStatus.ENABLED,
        priority=95,
    ),
    NewsSource(
        source_id="hochi_giants_x",
        name="Sports Hochi Giants X",
        source_type=SourceType.WEBSITE,
        base_url="https://x.com/hochi_giants",
        is_official=False,
        status=SourceStatus.ENABLED,
        priority=94,
    ),
    NewsSource(
        source_id="hochi_giants_articles",
        name="Sports Hochi Giants Articles",
        source_type=SourceType.WEBSITE,
        base_url="https://hochi.news/giants/",
        is_official=False,
        status=SourceStatus.ENABLED,
        priority=92,
    ),
    NewsSource(
        source_id="hochi_giants_instagram",
        name="Sports Hochi Giants Instagram",
        source_type=SourceType.WEBSITE,
        base_url=("https://www.instagram.com/sportshochi_giants/"),
        is_official=False,
        status=SourceStatus.PAUSED,
        priority=85,
    ),
)
